field: cbec6195-2d3a-45e1-9e20-b7693d4c6eb5
fieldLayouts:
  2ef06e10-462d-46d4-b32a-4dde875f033c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fb4931fd-5863-458a-866c-128bab0a043c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e31cadbd-54e2-45c3-ace7-9d3cd3e41917
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 691c3cea-9b65-4f95-a353-421009e2d4fd
        userCondition: null
fields:
  fb4931fd-5863-458a-866c-128bab0a043c:
    columnSuffix: qsnnbtum
    contentColumnType: text
    fieldGroup: null
    handle: track
    instructions: null
    name: Track
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: track
name: Track
sortOrder: 1
