fieldLayouts:
  e2d3aa50-8b5a-476c-8652-95294c9dd0d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23ae48e8-d802-4b4e-a548-4bdb21924187
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 810ffced-40f8-4288-b700-feca32601c70 # About Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b4d642f-90ba-4fc5-954b-4cd6990dcb30
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 94794f26-22b3-4740-ad7f-918f14a7e25a # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62772346-05de-4a54-a58d-dcf26ec21629
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03cca53a-c41a-4814-ba8e-b909859d0fdf
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 4b085c5b-cbde-4cea-8d32-e833e7e3fc17 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
