fieldLayouts:
  52dc3b7e-9519-487e-af1c-07d38afa9083:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d8cbe3f9-e275-40fa-8c9f-3e2b4fdabc5a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4443b572-3e49-4a10-812a-9e83b22e2312 # artists
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0e6fec7-24fb-40c8-b0a5-6ac347a0d598
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dfd3e2de-10fc-435b-a7fb-4ca2174bc169 # Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27950a32-cbec-4f5e-a16e-db9f7f0b073d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2caeb9e6-de4e-4b7d-b034-b8d7df9eea55 # Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 711abf7a-e9f6-4bb7-a3cc-da2fbcc692f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbec6195-2d3a-45e1-9e20-b7693d4c6eb5 # tracklist
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eab5abd-b7a8-487b-97be-7b4705822433
            userCondition: null
            warning: null
            width: 100
        name: 'Item Information'
        uid: 1064ff7a-5640-4669-a205-cd685abedec8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 446a111b-09c6-4903-840d-269957206f95 # Unique
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d125b9b-0326-4984-a609-0650e5902288
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eecdfa60-7de8-4d9a-ad1b-9b634842f8e3 # Acquisition Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12ae4c8a-890e-4d69-bdb9-37ea2e7fe267
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55a62cf6-085d-4d8a-b686-108d92b8bf48 # Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e14b060d-efdb-4459-a995-08913b7668f6
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: 730c228b-44df-4973-8295-fa44aea8fcc2
        userCondition: null
handle: album
hasTitleField: true
name: Album
section: 5de137c5-736f-4994-9fe8-109f6002e489 # Music
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
