fieldLayouts:
  906659ab-eab2-4480-a635-179be454f384:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 89d3172b-5b0d-4a86-ae8e-1f79b45da29c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1df5f52b-1aff-47c7-9b05-252262954c41 # Artist/Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34df00f8-2964-42d6-a1ed-a7f2da5aa1f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dfd3e2de-10fc-435b-a7fb-4ca2174bc169 # Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d58e172b-6d1b-4d2b-a774-b33cf9455e9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2caeb9e6-de4e-4b7d-b034-b8d7df9eea55 # Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d3cc7ad-e179-4685-88a1-d85b0ed5364f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 446a111b-09c6-4903-840d-269957206f95 # Unique
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26fd1a93-99d4-45f8-8ed0-76101caccf5f
            userCondition: null
            warning: null
            width: 100
        name: 'Item Information'
        uid: b7276810-7df4-4e4a-8e65-3117c6cf41fe
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: eecdfa60-7de8-4d9a-ad1b-9b634842f8e3 # Acquisition Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c969444-8cf4-4510-aae5-ff0eba5d6165
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55a62cf6-085d-4d8a-b686-108d92b8bf48 # Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8198d13-7f52-4670-8ba1-6c23f83a0c51
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: 3abffa90-c9cc-484d-9315-1f037699a35a
        userCondition: null
handle: mixtape
hasTitleField: true
name: Mixtape
section: 5de137c5-736f-4994-9fe8-109f6002e489 # Music
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
