fieldLayouts:
  2e21b04f-4a28-4905-88c8-787214ea312e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fe41c41a-35a6-458e-b8ce-ad8cbe29563f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 94794f26-22b3-4740-ad7f-918f14a7e25a # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31695386-79eb-44af-b8b2-97aa562404e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d803a54-0499-4911-9b33-07713cb040e2
        userCondition: null
handle: styleGuide
hasTitleField: false
name: 'Style Guide'
section: f0ef7e02-7ddf-419c-85af-a6d53fcb59ca # Style Guide
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
