baseUrl: 'http://musicalarchive.localhost/'
enabled: true
handle: default
hasUrls: true
language: en-GB
name: musicalarchive
primary: true
siteGroup: 06082fde-cddb-44bb-bce6-e870b82add2e # musicalarchive
sortOrder: 1
