columnSuffix: null
contentColumnType: string
fieldGroup: 282ab7e6-9aad-4a08-be01-6e500f83865b # Collection FIelds
handle: tracklist
instructions: null
name: tracklist
searchable: true
settings:
  contentTable: '{{%matrixcontent_tracklist}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
