columnSuffix: ivnlsrrb
contentColumnType: boolean
fieldGroup: 282ab7e6-9aad-4a08-be01-6e500f83865b # Collection FIelds
handle: unique
instructions: 'Is this item one-of-a-kind?'
name: Unique
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
