dateModified: 1668443896
email:
  fromEmail: zach@helixsoftware.uk
  fromName: musicalarchive
  transportType: craft\mail\transportadapters\Sendmail
fs:
  blog:
    hasUrls: true
    name: Blog
    settings:
      path: '@webroot/assets/blog'
    type: craft\fs\Local
    url: '@web/assets/blog'
  collectionPhotos:
    hasUrls: true
    name: 'Collection Photos'
    settings:
      path: '@webroot/assets/collections'
    type: craft\fs\Local
    url: '@web/assets/collections'
  general:
    hasUrls: true
    name: General
    settings:
      path: '@webroot/assets/general'
    type: craft\fs\Local
    url: '@web/assets/general'
meta:
  __names__:
    1c98138d-1888-4dc8-adfd-4f3c0a932bba: Artist # Artist
    1df5f52b-1aff-47c7-9b05-252262954c41: Artist/Author # Artist/Author
    2caeb9e6-de4e-4b7d-b034-b8d7df9eea55: Photo # Photo
    3befbf7a-2151-4083-a9a8-10a89575101d: 'Post Categories' # Post Categories
    3e021f99-bf84-4265-b5da-615ca8c48aa6: Blog # Blog
    3f26b933-c4ee-41fc-8507-826fe25f197d: Album # Album
    4b085c5b-cbde-4cea-8d32-e833e7e3fc17: About # About
    5de137c5-736f-4994-9fe8-109f6002e489: Music # Music
    6ccdcca2-31c8-4fee-bf35-1b3d007e5ff4: Artist/Author # Artist/Author
    7e86ba13-ef94-468b-88d6-019ed278001b: Track
    8cf3e7ee-e333-4167-8379-2d517bee2677: 'Site Description' # Site Description
    8f388929-8455-4fd7-8f9e-7bb45d20c016: musicalarchive # musicalarchive
    35b36be4-834d-414f-af03-5b4041ca5436: 'Site Information' # Site Information
    55a62cf6-085d-4d8a-b686-108d92b8bf48: Notes # Notes
    64d7f960-7f9d-4af1-9c22-93abee4cd24c: 'Blog Fields' # Blog Fields
    74ce1003-afd5-4aa5-94d4-4a5142ab97a2: 'Collection Photos' # Collection Photos
    79ae642c-990d-4d9b-8317-4cc8c26b399f: Artist # Artist
    282ab7e6-9aad-4a08-be01-6e500f83865b: 'Collection FIelds' # Collection FIelds
    446a111b-09c6-4903-840d-269957206f95: Unique # Unique
    517be0c0-6372-4444-9ba9-5bbaf05c168c: Common # Common
    634a1f41-8434-47af-9ff4-0dc5ff872cbd: 'Global Fields' # Global Fields
    639f7ec5-55ce-4c1d-9e03-c3df12727378: 'Feature Image' # Feature Image
    810ffced-40f8-4288-b700-feca32601c70: 'About Image' # About Image
    5483b3c4-b3d6-4315-a7ab-457d23d0a267: Text # Text
    06082fde-cddb-44bb-bce6-e870b82add2e: musicalarchive # musicalarchive
    7654d583-cba2-4e65-8f71-26227bf7ee8c: Mixtape # Mixtape
    8766ac03-8149-44eb-b661-5c6277fc409a: 'Home Section' # Home Section
    58572b0a-71e8-4883-b30f-97fb90d22afb: Content # Content
    77251f66-ed5e-4240-ace2-10884819d0f8: Home # Home
    94794f26-22b3-4740-ad7f-918f14a7e25a: 'Post Content' # Post Content
    47306389-8bad-47ef-9573-e3ad6dfb9e39: Content # Content
    a96750cb-fdc6-41d9-bbc6-4436fc28f38c: Home # Home
    aa94fc81-cb07-4ebb-bba9-8c1f999ce3b6: Blog # Blog
    aaa2bdd2-d65f-4a85-846e-5246b789d999: 'Singles Fields' # Singles Fields
    bd7b6869-5740-4ee2-9225-67bbe45f8862: Text # Text
    c0652f0d-d055-4153-aa0f-be6c1952c9b4: Image # Image
    cbec6195-2d3a-45e1-9e20-b7693d4c6eb5: tracklist
    d33c00e7-61c8-4013-a389-f165b90f06d3: Title # Title
    d2987ff5-6fda-44a2-9c02-fbd08daa8162: Title # Title
    dfd3e2de-10fc-435b-a7fb-4ca2174bc169: Media # Media
    e30d3f1a-6d5e-4baf-ac13-25589205be7c: Default # Default
    e531e94f-86e9-4230-9927-e07bd8e2c2d3: General # General
    ee1c91a8-69c9-4288-bf31-80a8b1bf70c8: Summary # Summary
    eecdfa60-7de8-4d9a-ad1b-9b634842f8e3: 'Acquisition Date' # Acquisition Date
    f0ef7e02-7ddf-419c-85af-a6d53fcb59ca: 'Style Guide' # Style Guide
    f28e2a24-929c-4016-be37-3a8c585ecccf: 'Style Guide' # Style Guide
    f92a785f-4bee-498f-a032-afe673cb25e6: About # About
    fb4931fd-5863-458a-866c-128bab0a043c: Track
    fc8925c5-abaa-491d-bbf3-eeea98f286bd: 'Blog Categories' # Blog Categories
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: musicalarchive
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
