defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  8f388929-8455-4fd7-8f9e-7bb45d20c016: # musicalarchive
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
