defaultPlacement: end
enableVersioning: true
handle: music
name: Music
propagationMethod: all
siteSettings:
  8f388929-8455-4fd7-8f9e-7bb45d20c016: # musicalarchive
    enabledByDefault: true
    hasUrls: true
    template: music/_entry
    uriFormat: 'music/{slug}'
type: channel
